### ISSUE TITLE
When I use the command line you provided to perform the training, the program keeps getting stuck in one state

### ISSUE THREAD

**Issue by BmonsterYJ** [jswati31/stage#1]
Thanks a lot to the authors for the wonderful work.I'm having some issues training my model. When I use the command line you provided to perform the training, the program keeps getting stuck in one state, as follows:                                                               
Loading configs\stage_transformer.json
Written Config file at result
STAGE_Transformer
*******Loading pretrained GazeCLR model********
model [STAGE_Transformer] was created
2024-04-17 12:29:40,295 root        : INFO     ------- Initializing dataloaders --------
data/Gaze360\train.txt
Skipped 1.0
data/Gaze360\validation.txt
Skipped 1.0
2024-04-17 12:29:45,765 root        : INFO     ------- Initializing model --------
2024-04-17 12:29:45,767 root        : INFO     Trainable Parameters: 11.422M      
2024-04-17 12:29:45,770 root        : INFO     Training                                                                                                                                        I hope to have your help and I will be very grateful

**Comment by jswati31** [comment]
Hello, thank you for your interest in our work. Can you kindly share the exact command line you are running? 
Also, which line of the code you are getting stuck? Can you share file name and line number?

**Comment by BmonsterYJ** [comment]
command line I use is : python main_gaze360.py --config_json configs/stage_lstm.json --save_path resualt --spatial_model proposed. When I enter debugging mode of main_gaze360.py,on line 306, it seemed like I had entered a dead loop  when loading the training data.Then entering train_utils.py, I found that 'out' always been 0.

**Comment by jswati31** [comment]
In the config/default.json file, please make sure you have right path for the datasets you are using. And dataloader is initializing properly. I hope this helps.
